# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quotes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quotes
  pod 'Google-Mobile-Ads-SDK'
  target 'quotes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'


    pod 'react-native-mail', :path => '../node_modules/react-native-mail'


  end

  target 'quotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
